---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: src
- name: ops.git
- name: img

outputs: []

params:
  ENV:
  JUMPBOX_SSH_KEY:

run:
  path: src/ci/build.sh
