---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: govau/cga-cf-bosh-cli
    tag: latest

inputs:
- name: src
- name: ci
- name: ca
- name: img

outputs: []

params:
  ENV:
  JUMPBOX_SSH_KEY:
  JUMPBOX_SSH_PORT:
  JUMPBOX_SSH_L_HOST:

run:
  path: ci/ci/build.sh
