---
jobs:
- name: kinesis-d
  serial: true
  plan:
  - do:
    - get: src
    - task: build
      file: src/ci/build.yml
      params:
        DOMAIN: system.d.cld.gov.au
    - put: d-cf
      params:
        manifest: build/manifest.yml
        path: build
        current_app_name: kinesis
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: kinesis-y
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - kinesis-d
    - task: build
      file: src/ci/build.yml
      params:
        DOMAIN: system.y.cld.gov.au
    - put: y-cf
      params:
        manifest: build/manifest.yml
        path: build
        current_app_name: kinesis
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: kinesis-b
  serial: true
  plan:
  - do:
    - get: src
      passed:
      - kinesis-y
    - task: build
      file: src/ci/build.yml
      params:
        DOMAIN: system.b.cld.gov.au
    - put: b-cf
      params:
        manifest: build/manifest.yml
        path: build
        current_app_name: kinesis
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
resources:
- name: src
  type: git
  source:
    uri: https://github.com/govau/cga-firehose-to-kinesis
    branch: master
- name: d-cf
  type: cf
  source:
    api: https://api.system.d.cld.gov.au
    username: ci-system-kinesis
    password: ((d-password))
    organization: system
    space: kinesis
- name: y-cf
  type: cf
  source:
    api: https://api.system.y.cld.gov.au
    username: ci-system-kinesis
    password: ((y-password))
    organization: system
    space: kinesis
- name: b-cf
  type: cf
  source:
    api: https://api.system.b.cld.gov.au
    username: ci-system-kinesis
    password: ((b-password))
    organization: system
    space: kinesis
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource