---
jobs:
- name: kinesis-build-container-image
  serial: true
  plan:
  - do:
    - get: src
      trigger: true
    - put: img
      params:
        build: src
      get_params: {skip_download: true}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
- name: kinesis-deploy-d
  serial: true
  plan:
  - do:
    - get: src
      passed: [kinesis-build-container-image]
    - get: img
      passed: [kinesis-build-container-image]
      params: {skip_download: true}
      trigger: true
    - get: ops.git
    - task: build
      file: src/ci/build.yml
      params:
        ENV: d
        JUMPBOX_SSH_KEY: ((jumpbox-key.private_key))
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: $BUILD_JOB_NAME SUCCESS
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
    on_failure:
      put: slack
      params:
        text: |
          :x: $BUILD_JOB_NAME FAILED
          <$ATC_EXTERNAL_URL/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
resources:
- name: src
  type: git
  source:
    uri: https://github.com/govau/cga-firehose-to-kinesis
    branch: master
- name: img
  type: docker-image
  source:
    repository: ((aws_repository))
    aws_access_key_id: ((aws_access_key_id))
    aws_secret_access_key: ((aws_secret_access_key))
- name: ops.git
  type: git
  source:
    branch: master
    paths:
    - terraform/sshca-ca.pub
    private_key: ((ops-git-deploy-key.private_key))
    uri: git@github.com:AusDTO/ops.git
- name: slack
  type: slack-notification
  source:
    url: ((slack-webhook-url))
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
